version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: farmtatva-db-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: farmer
      MYSQL_PASSWORD: fresh@tomato
      MYSQL_DATABASE: farmtatva

    ports:
      - "3306:3306"

    volumes:
      - mysqldata:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

    deploy:
      resources:
        limits:
          memory: 2g

    command: >
      --default-authentication-plugin=mysql_native_password
      --max_connections=200

volumes:
  mysqldata:
